# Generated by Django 5.2.17 on 2026-09-15 20:17

import moodboards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodboard',
            name='palette',
            field=models.JSONField(blank=True, default=list, validators=[moodboards.models.validate_palette]),
        ),
    ]
